# Generated by Django 4.0.4 on 2022-10-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("name", models.CharField(max_length=150)),
                ("first_surname", models.CharField(max_length=150)),
                ("last_surname", models.CharField(blank=True, default=None, max_length=150, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=12)),
            ],
            options={
                "db_table": "booking",
            },
        ),
    ]
