# Generated by Django 4.0.4 on 2022-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(max_length=25),
        ),
    ]
