# Generated by Django 3.1.7 on 2021-03-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0006_auto_20210316_1436"),
        ("address", "0003_auto_20210316_1221"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseModel",
            fields=[
                ("title", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                ("active", models.BooleanField(default=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="address.addressmodel",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(to="service.ServiceModel"),
                ),
            ],
            options={"db_table": "house"},
        )
    ]
