# Generated by Django 3.1.7 on 2021-03-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wifi", "0001_initial"),
        ("service", "0006_auto_20210316_1436"),
        ("address", "0003_auto_20210316_1221"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                ("active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.addressmodel",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(to="service.ServiceModel"),
                ),
                (
                    "wifi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wifi.wifimodel",
                    ),
                ),
            ],
            options={"db_table": "house"},
        )
    ]
