# Generated by Django 3.1.7 on 2021-03-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("house", "0001_initial")]

    operations = [migrations.RemoveField(model_name="housemodel", name="wifi")]
