# Generated by Django 3.1.7 on 2021-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("house", "0002_remove_housemodel_wifi")]

    operations = [
        migrations.AlterModelOptions(
            name="housemodel",
            options={"verbose_name": "House", "verbose_name_plural": "Houses"},
        ),
        migrations.RenameField(
            model_name="housemodel", old_name="createdAt", new_name="created"
        ),
        migrations.RenameField(
            model_name="housemodel", old_name="updatedAt", new_name="updated"
        ),
    ]
