# Generated by Django 3.1.7 on 2021-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("house", "0004_auto_20210317_1620")]

    operations = [
        migrations.RemoveField(model_name="housemodel", name="services")
    ]
