# Generated by Django 3.1.7 on 2021-03-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_housemodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='cover',
            field=models.TextField(default=None),
        ),
    ]
