# Generated by Django 3.1.7 on 2021-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_housemodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
