# Generated by Django 3.1.7 on 2021-04-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0007_auto_20210408_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='house.housemodel')),
            ],
            options={
                'verbose_name': 'Property Gallery',
                'verbose_name_plural': 'Property Gallery',
                'db_table': 'gallery',
            },
        ),
    ]
