# Generated by Django 3.1.7 on 2021-03-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insightmodel',
            old_name='image',
            new_name='cover',
        ),
    ]
