# Generated by Django 3.1.7 on 2021-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=16)),
                ("zipCode", models.IntegerField(max_length=5)),
                ("colony", models.CharField(max_length=128)),
                ("municipality", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=64)),
                ("country", models.CharField(default="MX", max_length=2)),
                ("references", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "address"},
        )
    ]
