# Generated by Django 3.1.7 on 2021-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("address", "0003_auto_20210316_1221")]

    operations = [
        migrations.AlterModelOptions(
            name="addressmodel",
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.RenameField(
            model_name="addressmodel", old_name="createdAt", new_name="created"
        ),
        migrations.RenameField(
            model_name="addressmodel", old_name="updatedAt", new_name="updated"
        ),
    ]
