# Generated by Django 4.0.4 on 2022-10-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_surname",
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="last_surname",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
