# Generated by Django 4.0.4 on 2022-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_first_surname_user_last_surname_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_surname",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
