# Generated by Django 3.1.7 on 2021-03-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("service", "0002_auto_20210316_0654")]

    operations = [migrations.AlterModelTable(name="service", table="service")]
