# Generated by Django 3.1.7 on 2021-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service", "0004_auto_20210316_0918")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
