# Generated by Django 3.1.7 on 2021-03-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("service", "0005_auto_20210316_0920")]

    operations = [
        migrations.RenameModel(old_name="Service", new_name="ServiceModel")
    ]
