# Generated by Django 3.1.7 on 2021-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("service", "0006_auto_20210316_1436")]

    operations = [
        migrations.AlterModelOptions(
            name="servicemodel",
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RenameField(
            model_name="servicemodel", old_name="createdAt", new_name="created"
        ),
        migrations.RenameField(
            model_name="servicemodel", old_name="updatedAt", new_name="updated"
        ),
    ]
