# Generated by Django 3.1.7 on 2021-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_remove_housemodel_services"),
        ("service", "0007_auto_20210317_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemodel",
            name="houses",
            field=models.ManyToManyField(
                related_name="services", to="house.HouseModel"
            ),
        )
    ]
