# Generated by Django 3.1.7 on 2021-03-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_remove_housemodel_wifi"),
        ("wifi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wifimodel",
            name="house",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="house.housemodel",
            ),
        )
    ]
