# Generated by Django 3.1.7 on 2021-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wifi", "0002_wifimodel_house")]

    operations = [
        migrations.AlterModelOptions(
            name="wifimodel",
            options={
                "verbose_name": "WiFi",
                "verbose_name_plural": "WiFi Networks",
            },
        ),
        migrations.RenameField(
            model_name="wifimodel", old_name="createdAt", new_name="created"
        ),
        migrations.RenameField(
            model_name="wifimodel", old_name="updatedAt", new_name="updated"
        ),
    ]
