# Generated by Django 3.1.7 on 2021-03-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_auto_20210317_1620"),
        ("wifi", "0003_auto_20210317_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wifimodel",
            name="house",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wifi",
                to="house.housemodel",
            ),
        )
    ]
